### ISSUE TITLE
6D poses groundtruth in real_objects.zip

### ISSUE THREAD

**Issue by gaobaoding** [IRVLUTD/fewsol-toolkit#1]
Dear authors,

thanks first for providing this useful and diverse dataset. In the paper you said you also save the 6D poses for the real_object dataset. What I found is the xxxxxx-meta.mat for each image and inside has 7-dim vectors for each marker and a 9-dim "joint_position". However I didn't find the translation and rotation matrix for each image. Could you explain what these values are and where you store the 6D pose groundtruth? Thanks!

**Comment by yuxng** [comment]
Hello,
The 7-dim vectors for the marker is the pose of the marker. The first 3 numbers are translation. The last 4 numbers are quaternion.
To obtain the object pose, you can use this function to compute it:
https://github.com/IRVLUTD/fewsol-toolkit/blob/d458820457497fdba5729bc574e6744cff26fcf6/tools/image_loader.py#L146
meta['center'] = RT_centers[index] in the code is the object pose.

**Comment by gaobaoding** [comment]
Hi @yuxng,
Thank you so much. Will try it out!
